name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -v github.com/projectdiscovery/dnsx/cmd/dnsx
          go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
          go get -v github.com/projectdiscovery/httpx/cmd/httpx
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
          go get -u github.com/ffuf/ffuf
        shell: bash


      - name: Running naabu to check top all ports
        run: |
          naabu -iL input/target.txt  -rate 10000 -p - | tee output/active_ports.txt
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -title
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash
        
      - name: Xray scan urls
        run: |
          wget https://github.com/chaitin/xray/releases/download/1.7.1/xray_linux_amd64.zip
          unzip xray_linux_amd64.zip
          mv xray_linux_amd64 xray
          set +e ;for i in $(cat output/active_urls.txt ); do ./xray webscan --basic-crawler $i --html-output output/`date +%Y%m%d%H%M%S`.html;done
          cat output/*.html >> output/xray.html
        shell: bash
        
      - name: Running dirscan 
        run: |
          wget https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
          mkdir dirout
          set +e ;time for i in $(cat output/active_urls.txt );do ffuf -w dicc.txt -u $i/FUZZ -t 200 -mc 200 -ac -recursion -v -of csv -o dirout/`date +%Y%m%d%H%M%S`.csv; done
          cat dirout/*.csv >> output/dirout.csv
        shell: bash

        
      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/active_ports.txt
          git add output/active_urls.txt
          git add output/xray.html
          git add output/dirout.csv
      - name: Commit results to Github
        run: |
          git config --local user.email "admin@inbug.org"
          git config --global user.name "inbug-team"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
