name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev git python3-pip
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -v github.com/projectdiscovery/dnsx/cmd/dnsx
          go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
          go get -v github.com/projectdiscovery/httpx/cmd/httpx
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
          go get -v github.com/projectdiscovery/mapcidr/cmd/mapcidr
          go get -u github.com/ffuf/ffuf
        shell: bash


      - name: Running naabu to check top 1000 ports
        run: |
          mapcidr -l input/target.txt -silent > input/cidr.txt
          naabu -l input/cidr.txt  -rate 10000 -top-ports 1000 | tee output/active_ports.txt
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -title
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash
        
      - name: Runing FingerPrint
        run: |
          wget https://github.com/EdgeSecurityTeam/EHole/releases/download/3.0/Ehole3.0-linux.zip
          unzip Ehole3.0-linux.zip
          chmod +x Ehole3.0-linux
          ./Ehole3.0-linux -l output/active_urls.txt -json output/active_fingerprint.txt
        shell: bash  
        
      - name: Running dirscan 
        run: |
          wget https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
          mkdir dirout
          set +e ;time for i in $(cat output/active_urls.txt );do ffuf -w dicc.txt -u $i/FUZZ -t 200 -mc 200 -ac -recursion -v -of csv -o dirout/`date +%Y%m%d%H%M%S`.csv; done
          cat dirout/*.csv >> output/dirout.csv
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/active_ports.txt
          git add output/active_urls.txt
          git add output/dirout.csv
          git add output/active_fingerprint.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "guiyingchongchong@qq.com"
          git config --global user.name "sharp-shooter"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
